### ISSUE TITLE
Uso de Material UI

### ISSUE THREAD

**Issue by Nicolasramos411** [IIC2513-2022-2/project#1]
Hola! 

En el enunciado salía que no se pueden usar librerias de componentes como bootstrap pero quería saber si esto aplica para el caso específico de la libreria [MUI](https://mui.com/) (Material-UI) ya que, a pesar de ser una librería de componentes, permite usar preprocesadores de CSS como [StyledComponents](https://styled-components.com/) o [Emotion](https://emotion.sh/docs/introduction) por lo que, los componentes pueden ser totalmente modificables y simplemente te entregan una 'estructura'.

A nivel profesional, MUI lo utilizan empresas como Examedi, por lo que podría ser un plus aprenderlo utilizandolo en el proyecto.

**Comment by valeeeriquelme** [comment]
Respuesta muy similar a la dada en https://github.com/IIC2513-2022-2/project/issues/10

En particular para esta librería, se deberá acordar con el ayudante las vistas en las que "se permitirá" su uso.
