### ISSUE TITLE
[Entrega 1] Uso de React y Styled-components ó Emotion

### ISSUE THREAD

**Issue by Nicolasramos411** [IIC2513-2022-2/project#10]
Hola!

Realmente son 2 preguntas que están muy relacionadas:

- Se puede utilizar React para la creación de páginas estáticas con HTML y JS. Así podemos manejar de mejor manera los eventos.

- En el caso de que se pueda, se pueden utilizar librerias como Styled-components o emotion para manejar el CSS.

Gracias!

**Comment by valeeeriquelme** [comment]
1) No para la entrega 1. El uso de React empezará desde la entrega 2. 

2) Lo mismo que con react. Eso si, al entregar una ventaja a nivel de desarrollo (frameworks/librerías), los resultados exigidos irán acorde a esto. El detalle deberá ser manejado con el ayudante guía.
