### ISSUE TITLE
[Entrega 1] Uso de librerías de js 

### ISSUE THREAD

**Issue by diegocostares** [IIC2513-2022-2/project#14]
¡Hola!
Quería preguntar si es posible usar librerías de js en la entrega 1.
Específicamente quiero utilizar una librería llamada [vanilla tilt js](https://micku7zu.github.io/vanilla-tilt.js/) para darle una pequeña animación a unas "cajas" que ya tengo definidas en el html. Por lo que solo usaría el script para hacer las animaciones al pasar el cursor.

Tendría que añadir lo siguiente en mi `.html`:
```html
<script type="text/javascript" src="vanilla-tilt.js"></script>
```
Y esto en mi `.js`:
```js
VanillaTilt.init(document.querySelector(".mi-caja"), {
        max: 25,
        speed: 400
});
```

**Comment by valeeeriquelme** [comment]
Úsala nomás
