### ISSUE TITLE
[Entrega 1] Uso de libreria js (konva)

### ISSUE THREAD

**Issue by fernandosmither** [IIC2513-2022-2/project#15]
Hola!

Me gustaría utilizar la librería de js Konva. Es una librería de dibujo, la cual solo será utilizada para una vista específica, donde nos gustaría dibujar formas en un canvas.

Por ejemplo, para crear varios círculos dentro de un canvas se haría:
```javascript
<script src="https://unpkg.com/konva@8.3.12/konva.min.js"></script>
      function generateNode() {
        return new Konva.Circle({
          x: WIDTH * Math.random(),
          y: HEIGHT * Math.random(),
          radius: 50,
          fill: 'red',
          stroke: 'black',
        });
      }
```
ref: [https://konvajs.org/docs/sandbox/Canvas_Scrolling.html](https://konvajs.org/docs/sandbox/Canvas_Scrolling.html)

**Comment by valeeeriquelme** [comment]
Ok, para el caso de uso que indicas no hay problema.
