### ISSUE TITLE
[Entrega 2] Uso de imports en react para los css y js

### ISSUE THREAD

**Issue by lfb1206** [IIC2513-2022-2/project#16]
Hola, luego de ver las capsulas me quedo la duda de como se utilizan estos elementos en los component. Tambien me quedo la duda sobre el orden de las carpetas, dado que en la entrega 1 se solicitaba una distribución en especifico, pero en las capsulas solo se menciona styles ¿Donde quedan el resto de los assets (Imagenes y scripts)?

¡Muchas gracias!

**Comment by nanglada** [comment]
Hola! Sobre la distribución de los elementos en carpetas, dado que en esta entrega no se pide una estructura en específico, puedes ordenarlo de la forma que más te acomode, siempre que sea ordenado y entendible tanto para uds como para su ayudante. Por ejemplo, pueden tener una carpeta assets, que dentro incluya su carpeta imgs, scripts y styles.
