### ISSUE TITLE
Reglas de negocio

### ISSUE THREAD

**Issue by antoniablanco** [IIC2513-2022-2/project#17]
Hola, no entiendo bien a que se refieren con que las reglas de negocio sean navegables por el usuairio en la página. No se si existe algún ejemplo para poder guiarse?
Muchas gracias

**Comment by valeeeriquelme** [comment]
Simplemente que el usuario pueda acceder a estas, a través de la navbar por ejemplo, y leerlas. En caso de ser un documento muy extenso, se sugiere agregarle estilo para facilitar la comprensión del lector (un índice fixed que permita navegar por los distintos tópicos de forma más "dinámica", botones que te lleven a una sección siguiente, etc.)
