### ISSUE TITLE
Mockups Entrega 0

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2513-2022-2/project#2]
Hola,

Me gustaría saber:
1. ¿Se pueden hacer mockups feitos con power point no más?
2. Si es que mi juego se parece mucho a uno que ya existe (pero será más limitado), ¿se pueden usar como mockups screenshots del juego ya existente?

**Comment by valeeeriquelme** [comment]
1) Si, ojalaá ni "feitos", pero que sea claro para el ayudante entender los elementos base que van a ocupar
2) No. Deben ustedes fabricar sus mockups.
