### ISSUE TITLE
[Entrega 2] Incorporar React a proyecto existente

### ISSUE THREAD

**Issue by raibd** [IIC2513-2022-2/project#21]
Hola, no me queda tan claro como incorporar React al frontend que ya tenemos. ¿Solo hay que crear un proyecto de React encima (es decir, correr create-react-app) y después ordenar los archivos?

Gracias

**Comment by barbaraim** [comment]
Hola!

Más que nada, es mover las vistas existentes a un proyecto de React. 

Para ello, podrías poner cada vista en un componente distinto en un inicio. Luego podrías empezar a poner los subcomponentes que consideres necesarios.

Aunque no es necesariamente requerido en esta entrega, te puede servir Routing (Cápsula 5 de React) para poder hacer la navegación entre vistas.

Saludos
