### ISSUE TITLE
Index capsula 4

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2513-2022-2/project#23]
Hola ! En esta capsula 4: https://www.loom.com/share/22fad33ac4944773ba8e8774b9836024, se usa index dentro de la función props.list_symbols.map. ¿Para que sirve? Cuando lo printeo en Tile me da undefined.

**Comment by barbaraim** [comment]
Hola!

El uso de index en esa parte de la cápsula está asociado a la necesidad de tener una llave o key único que identifique a cada elemento del mappeo. Esto se describe en `https://reactjs.org/docs/lists-and-keys.html` . Básicamente, React necesita tener una forma de identificar cada elemento de este mappeo, para poder saber cuáles fueron agregados, modificados y/o eliminados en cada re-render.

En más detalle, usar index como key no es la mejor práctica en todos los casos. Normalmente se utilizan IDs o algo único para cada elemento. Pero en el caso de la cápsula, al no estar conectado al backend, no teníamos información del ID de cada casilla y era una lista fija en un inicio, por lo que usar index no afectaba. A la hora de conectar con backend, sí es recomendable utilizar un ID. 

Para más información:
- https://adhithiravi.medium.com/why-do-i-need-keys-in-react-lists-dbb522188bbb
- https://www.geeksforgeeks.org/reactjs-keys/
