### ISSUE TITLE
[Entrega 2] Problema con creacion de tabla intermedia en relacion N:N

### ISSUE THREAD

**Issue by nicoabarca** [IIC2513-2022-2/project#25]
Holaa 👋🏼 , con mi grupo tenemos una relación N:N en nuestra modelación de la base de datos de nuestro juego, la cual es la siguiente:
```
User.belongsToMany(Game, { through: 'UserGame' });
Game.belongsToMany(User, { through: 'UserGame' });
```
Según la documentación de Sequelize se debería crear un modelo y tabla intermedia con el nombre 'UserGame', pero al correr la migración y ver las tablas de nuestra base de datos, tal tabla no aparece.
¿Alguna idea de por qué esto esta ocurriendo o posible solución?
Gracias 😄

**Comment by valeeeriquelme** [comment]
La documentación indica que lo que se crea es un modelo, pero no una tabla. Para que la tabla sea generada, se debe crear también la migración. Quizás esta documentación los pueda ayudar https://medium.com/@andrewoons/how-to-define-sequelize-associations-using-migrations-de4333bf75a7 si es que aún no lo resolvieron.
