### ISSUE TITLE
Duda ctx.params

### ISSUE THREAD

**Issue by mhrobles** [IIC2513-2022-2/project#27]
Lo que sucede es que por alguna razón mi backend no detecta los params que se le entregan en las funciones de get o post, no se por que es esto, de hecho, cuando hago console.log(ctx.params) solo me entrega {}

**Comment by valeeeriquelme** [comment]
El problema podría deberse a varias cosas, desde a como estás enviando tus parámetros a como los estás recibiendo en el endpoint. Tendría que ver tu código para entender mejor. Si no lo has resuelto y me puedes adjuntar screenshots de tu endpoint y donde lo llamas podría ayudarte más.
