### ISSUE TITLE
[Entrega 0] Reglas del negocio

### ISSUE THREAD

**Issue by pablo-soto** [IIC2513-2022-2/project#3]
La entrega:
3.Las reglas del negocio que gestionará el servidor para tratar cada interacción.

Queria preguntar a que se refiere con las reglas del negocio en el enunciado de entrega 0

**Comment by valeeeriquelme** [comment]
Las reglas de negocio se refiere a cómo serán procesadas las jugadas que hagan los jugadores. Es la lógica del juego. Por ejemplo, si en un juego de ataque un jugador en su turno se mueve hacia una casilla continua, el servidor podría procesar esta jugada de la siguiente forma: revisar si hay ejércitos en la casilla a la que se movió, revisar si estos ejércitos son de otro jugador o de quien se movió, revisar los puntos de ataque y defensa de cada uno, calcular quien gana (random, se comparan puntos, alguna función, etc), quitarle al perdedor esos ejércitos, finalizar jugada. (Esto es solo un ejemplo, no siempre va a ser así, depende de su juego).

Te recomiendo revisar los archivos ocupados en la ayudantía 0 donde se muestra un ejemplo de como realizar esto. Pueden armarlo de otra forma, pero la idea es que sean detallados para facilitar luego el desarrollo.
