### ISSUE TITLE
Error React no me funciona bien

### ISSUE THREAD

**Issue by Fercho19** [IIC2513-2022-2/project#32]
Hola, tengo un problema con React el cual no pude resolver en la Sala de Dudas. Al momento de correr el back y el front  (utilizando yarn start al igual que mis otros dos compañeros) en mi caso se demora aproximadamente 3 mins en abrir React en google (eso como primer mal funcionamiento lo cual lo vuelve muy tedioso). Una vez abierto, al realizar algún cambio en el código y guardar los cambios, React no recibe ese cambio o más bien no esta funcionando "en vivo" por lo que para ver el cambio debo correr nuevamente React (lo cual tarda 3 mins o más) y se vuelve muy lento avanzar en el proyecto. 

No he podido solucionarlo en varios días. Se agradece alguna solución.
Muchas gracias

**Comment by valeeeriquelme** [comment]
Con que estás trabajando? Windows/WSL/...

**Comment by domingo2000** [comment]
Si estás en wsl con windows asegurate de clonar tu proyecto directo de la terminal de wsl. Si tienes tus archivos en los directorios de windows y abres el proyecto desde wsl tendrás problemas como los que mencionas. Esto debido a que linux y windows tienen sistemas de archivos separados. En resumen, trabaja todo directo en wsl, no copies pegues cosas con el windows Explorer, clona directo en la terminal de wsl con git y luego abres vscode y trabajas normalmente. Avisa si te funciona!
