### ISSUE TITLE
[Entrega 0] Semejanza puntos 2 y 11.

### ISSUE THREAD

**Issue by vcrb18** [IIC2513-2022-2/project#4]
Hola, tenemos una duda con los puntos 2 y 11 de esta entrega.
Básicamente en el punto 2 se pide una entrega de la aplicación de manera detallada describiendo las funcionalidades. Sin embargo, en el punto 11 se pide una descripción de los objetos y/o instancias que intervendrán en el juego, lo que finalmente es describir como funcionan estos, lo cual recae en describir las funcionalidades. Entonces no entendemos bien las diferencias entre estos dos puntos, sentimos que piden lo mismo.
Espero que se entienda el punto, y si no es así, si por favor me pueden aclarar las diferencias entre el punto 2 y 11 de la entrega, dado que siento que recaen en lo mismo.

**Comment by valeeeriquelme** [comment]
Hola, no son lo mismo en el sentido de que el primero (punto 2) está enfocado en la interacción del usuario con el juego y las acciones que puede hacer y la segunda (punto 11) con características de los elementos. Por ejemplo, si lo aplicamos al monopoly esto sería:

punto 2: El jugador puede comprar una propiedad.  
punto 11: Hay 3 tipos de propiedades, casas, edificios y hoteles. Las casas cuestan 1 peso, los edificios 100 y los hoteles 1000.

De todas maneras si te hace sentido incorporar el punto 11 en el 2, no hay problema. Pero que se note que se trabajaron ambos puntos.  

Te recomiendo revisar los archivos ocupados en la ayudantía 0 donde se muestra un ejemplo de como realizar esto. Pueden armarlo de otra forma, pero la idea es que sean detallados para facilitar luego el desarrollo.

**Comment by vcrb18** [comment]
GRACIAS!
