### ISSUE TITLE
[Entrega 0] Punto 4. Mockup?

### ISSUE THREAD

**Issue by vcrb18** [IIC2513-2022-2/project#5]
Hola, no nos queda claro si en el punto 4 tenemos que hacer un mockup de la "landing page". Nos piden que la diseñemos, pero no habla de hacer un mock up, asique asumimos que hay que hacerlo y que ese es el diseño, aunque el enunciado no lo pida. ¿ Es esto lo que efectivamente nos pide el enunciado, o lo estamos entendiendo mal y hay que hacer otra cosa?

**Comment by valeeeriquelme** [comment]
Si, efectivamente es un mockup.
