### ISSUE TITLE
[Entrega 0] - Pequeñas variaciones al tipo de juego

### ISSUE THREAD

**Issue by valentin-diaz** [IIC2513-2022-2/project#6]
Hola, quería preguntar si es necesario que el tipo de juego que elijamos siga rigurosamente todos los puntos que aparecen el enunciado. Por ejemplo, hacer un juego de tipo aventura/descubrimiento pero cuyo objetivo sea ser el último en pie en vez de obtener cierta cantidad de recursos, o que creemos otra forma de curar al equipo en vez de la "zona cero" que aparece en el punto 12.
¿Podemos tomarnos esas libertades, manteniendo la esencia del tipo de juego?

**Comment by valeeeriquelme** [comment]
Si se pueden tomar esas libertades, de todas formas, consulten con su ayudante guía. En la reunión post entrega 0 el ayudante les dará feedback y los guiará sobre que cambios podrían implementar. 

Lo importante es que la dificultad no se reduzca, sino que, así como están pensándolo ustedes, si quieren sacar algo, lo reemplacen por otra cosa.
