### ISSUE TITLE
[Entrega 0] Dudas sobre reglas de tipo de juego

### ISSUE THREAD

**Issue by Yerko-Contreras** [IIC2513-2022-2/project#7]
Hola tengo unas dudas respecto al tipo de juego del punto 3 de un juego de aventura/descubrimiento.
- Es necesario que cada personaje tenga un registro de vida propio o como todos se mueven de forma simultánea se puede establecer solo una vida para todo el equipo. 
- ¿Se puede fijar un tiempo límite para realizar una jugada en un turno?

**Comment by valeeeriquelme** [comment]
1) Pueden proponer establecer solo una vida para el equipo, después el ayudante podría sugerirles cambiarlo según la dificultad general del juego propuesto
2) Si
